coverage:
    status:
        project:
            default: off
            variable-name:
                flags: variable_name
                target: 80%

flags:
    variable_name:
        paths:
            - packages/variable-name
    tests:
        paths:
            - tests/
